---
collections:
  - name: community.docker
  - name: community.general

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip

  # My roles
#  - name: Varssos.nomachine
#  - name: Varssos.chrome