---
- hosts: localhost
  become: yes

  pre_tasks:
    - name: Set ubuntu_codename fact
      import_role:
        name: ubuntu-codename

  tasks:
    - import_tasks: tasks/main.yml

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - dotfiles
    - chrome
    - fzf
    - grub-customizer
    - nomachine