---
- name: Add GPG key for Brave repository
  shell: sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg


- name: Add Brave repository
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

- name: Update apt packages cache
  apt:
    update_cache: yes

- name: Install Brave browser
  apt:
    name: brave-browser
    state: present
