---
- name: Add GPG key for Brave repository
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present

- name: Add Brave repository
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Update apt packages cache
  apt:
    update_cache: yes

- name: Install Brave browser
  apt:
    name: brave-browser
    state: present
