---
# Using shell because if you use builtin: ansible.builtin.apt_repository it takes wrong system codename. On Mint it takes Mint's like Victoria, but it should jammy!
- name: Add PPA repository for grub-customizer
  shell: sudo add-apt-repository ppa:danielrichter2007/grub-customizer -y

- name: Install Grub Customizer
  apt:
    update_cache: yes
    name: grub-customizer
    state: latest