---
- name: Download file .deb NoMachine
  get_url:
    url: "{{ nomachine_deb_url }}"
    dest: "/tmp/{{ nomachine_deb_file }}"

- name: Install NoMachine
  apt:
    deb: "/tmp/{{ nomachine_deb_file }}"
    state: present