---
- name: Install Signal
  ansible.builtin.include_role:
    name: signal

- name: Install Tailscale
  ansible.builtin.include_role:
    name: tailscale

# - name: Install Spotify
#   ansible.builtin.include_role:
#     name: spotify
#   ansible.builtin.include_role:
#     name: tailscale
