---
- name: Install Signal
  ansible.builtin.include_role:
    name: signal

- name: Install Tailscale
  ansible.builtin.include_role:
    name: tailscale

- name: Install xdotool
  ansible.builtin.include_role:
    name: xdotool
