---
- name: Install CIFS Utils pkg
  package:
    name: cifs-utils
    state: latest

- name: Handle local samba share
  block:
    - name: Create local mount point directory
      file:
        path: '{{ local_samba_mount_point_share }}'
        state: directory

    - name: Add local entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "//{{ homeserver_local_ip }}/{{ samba_export_share }} {{ local_samba_mount_point_share }} cifs username={{ homeserver_user_name }},password={{ samba_password }},domain=WORKGROUP 0 0"
        state: present
        backup: yes

    - name: Mount local Samba share 
      mount:
        path: '{{ local_samba_mount_point_share }}'
        src: "//{{ homeserver_local_ip }}/{{ samba_export_share }}"
        fstype: cifs
        opts: "username={{ homeserver_user_name }},password={{ samba_password }},domain=WORKGROUP"
        state: mounted
  when: mount_local_samba

- name: Handle tailscale samba share
  block:
    - name: Create tailscale mount point directory
      file:
        path: '{{ tailscale_samba_mount_point_share }}'
        state: directory
    - name: Add tailscale entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "//{{ homeserver_tailscale_ip }}/{{ samba_export_share }} {{ tailscale_samba_mount_point_share }} cifs username={{ homeserver_user_name }},password={{ samba_password }},domain=WORKGROUP 0 0"
        state: present
        backup: yes

    - name: Mount tailscale Samba share
      mount:
        path: '{{ tailscale_samba_mount_point_share }}'
        src: '//{{ homeserver_tailscale_ip }}/{{ samba_export_share }}'
        fstype: cifs
        opts: "username={{ homeserver_user_name }},password={{ samba_password }},domain=WORKGROUP"
        state: mounted
  when: mount_tailscale_samba